name: 'Send MS Teams notification'
description: 'Send a notification into an MS Teams channel'
inputs:
  title:
    description: 'Title for the notification'
    required: true
    type: string  
  text:
    description: 'Text for the notification'
    required: true
    type: string  
    default: Read the workflow logs for more information
  button_text:
    description: 'Text to display in the action button'
    required: true
    type: string
    default: "Go to workflow"
  url:
    description: 'Url for the action button'
    required: true
    type: string
  teams_webhook_url:
    description: 'Teams webhook url'
    required: true
    type: string
runs:
  using: "composite"
  steps:
      - id: send-notification
        name: Send MS Teams notification
        shell: bash
        env:
          button_url: ${{ inputs.url }}
          teams_webhook_url: ${{ inputs.teams_webhook_url }}
          title: ${{ inputs.title }}
          text: ${{ inputs.text}}
          button_text: ${{ inputs.button_text }}
        run: |
          # Send the notification
          set -e
          set -o pipefail

          inputs_url="${{ env.button_url }}"
          url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

          if [ ${#inputs_url} == 0 ] 
          then
            echo "No url given as input, using the default value: [$url]"
            inputs_url=$url
          fi
          export TEAMS_WEBHOOK=${{ env.teams_webhook_url }}
          . $GITHUB_ACTION_PATH/send-notification.sh "${{ env.title }}" "${{ env.text}}" "${{ env.button_text }}" "$inputs_url"
          
