name: Test the action
on:
  push:

jobs:
  test-the-action:
    name: test
    runs-on: k8s
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./
      with: 
        title: 'Title for the notification'
        text: 'Text for the notification'
        button_text: 'Text to display in the action button'
        url: "https://asml.com"
        teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK }}